pullRequests.grouping = [
  { name = "patches", "title" = "Patch updates", "filter" = [{"version" = "patch"}] }
]

updates.ignore = [
  // these will get updated along with pekko-actor, so no need to update them separately
  { groupId = "org.apache.pekko", artifactId = "pekko-actor-testkit-typed" },
  { groupId = "org.apache.pekko", artifactId = "pekko-actor-typed" },
  { groupId = "org.apache.pekko", artifactId = "pekko-slf4j" },
  { groupId = "org.apache.pekko", artifactId = "pekko-stream" },
  { groupId = "org.apache.pekko", artifactId = "pekko-testkit" },
]
